/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/PaperPlane.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const PaperPlane = (props) => {
  const { nodes, materials } = useGLTF("/models/PaperPlane.glb");
  return (
    <>
      <directionalLight position={[0, 3, 1]} intensity={0.1} />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Plane.geometry} material={materials.Red} />
      </group>
    </>
  );
};

useGLTF.preload("/models/PaperPlane.glb");
