/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Butterfly.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Butterfly(props) {
  const { nodes, materials } = useGLTF("/models/Butterfly.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["Node-Mesh"].geometry}
        material={materials.lambert3SG}
      />
      <mesh
        geometry={nodes["Node-Mesh_1"].geometry}
        material={materials.lambert4SG}
      />
      <mesh
        geometry={nodes["Node-Mesh_2"].geometry}
        material={materials.lambert2SG}
      />
      <mesh
        geometry={nodes["Node-Mesh_3"].geometry}
        material={materials.lambert5SG}
      />
    </group>
  );
}

useGLTF.preload("/models/Butterfly.glb");
